### ISSUE TITLE
Unable to deserialize to non-iterable objects

### ISSUE THREAD

**Issue by akursar** [hampsterx/async-kinesis#22]
Hey @hampsterx , I tried using a custom Serializer that would serialize/deserialize some custom classes. They're actually protobuf messages, but that's not important. I run into a problem in the `Consumer.__anext__` method where it looks like it's checking for a special checkpoint message in the queue. Specifically, I hit:

    File "/usr/local/lib/python3.8/site-packages/kinesis/consumer.py", line 390, in __anext__
    if item and "__CHECKPOINT__" in item:
    TypeError: argument of type 'TestMessage' is not iterable

I think the "in" check here works for dicts and strings, but can cause problems for other types. I wonder if the check can be made more specific, maybe by using a Checkpoint class, or a named tuple, and/or by checking for that __checkpoint__ using hasattr? I'm not sure if there are any other areas where using non-string/non-dict messages can cause unexpected problems, or how large a refactor checking the checkpoint message type might be. Minimally I guess just catching a TypeError somewhere around there is a simpler solution for me. What do you think?

**Comment by hampsterx** [comment]
cool, yeah seems easiest to just check if its string (or bytes like) rather than custom serializer for checkpointer. see #23
